[[pages]]
name = "Prompt Engineering & RAG"
icon = ":book:"
is_section = true

[[pages]]
path = "app/_pages/prompt_page.py"
name = "Prompt Engineering App"
icon = ":beginner:"

[[pages]]
path = "app/_pages/rag_page.py"
name = "RAG App"
icon = "📄"
